### ISSUE TITLE
Missing License for the Theme

### ISSUE THREAD

**Issue by addyi** [TEParsons/mkdocs-landing#2]
Hi @TEParsons,

First off, thank you for creating and sharing this wonderful theme! 👏😍 I'm currently building a website with it and absolutely love the design.

However, I noticed that the repository doesn't include a license. Without one, it’s technically not permitted for me—or others—to use, modify, or distribute the theme legally.

Would you consider adding a license? A straightforward option might be the BSD license that MkDocs itself uses. You could simply copy/paste their license and add your name at the top: [MkDocs BSD License](https://github.com/mkdocs/mkdocs/blob/master/LICENSE).

Thank you again for your work and for providing such an amazing theme! 🙇‍♂️

**Comment by TEParsons** [comment]
Good point, I'll stick a standard creative commons on, thanks :) Please do send me the link to your site when it's done, I'm interested to see how people are using the theme!
